# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QuickStart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QuickStart
  pod 'AdyenReactNative', :path => '../node_modules/adyen-react-native'

  target 'QuickStartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Adyen'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
